name: release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      release-browser: ${{ steps.release.outputs['packages/browser--release_created'] || false }}
      release-core: ${{ steps.release.outputs['packages/core--release_created'] || false }}
      release-tmdb: ${{ steps.release.outputs['packages/tmdb--release_created'] || false }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
  release-packages:
    name: release-packages
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: contains(needs.release-please.outputs.*, 'true')
    strategy:
      matrix:
        package:
          - name: "@mdhs/browser"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-browser) }}
          - name: "@mdhs/core"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-core) }}
          - name: "@mdhs/tmdb"
            is-release: ${{ fromJSON(needs.release-please.outputs.release-tmdb) }}
        exclude:
          - package:
              is-release: false
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm publish --workspace ${{ matrix.package.name }} --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
